### ISSUE TITLE
Password not stored in Keychain

### ISSUE THREAD

**Issue by pierrec18** [NattyNarwhal/Submariner#125]
Hi all.

When I add a server (on Navidrome by the way) in Submariner, I can access my music.
After closing and re-opening the application, it gives me a "Wrong username/password (code 40)" error. After some research, I believe the application is unable to store the password in the keychain.

I have tried uninstalling / reinstalling / restarting / whatever and nothing works. Can you help me?
I don't have a problem with the application, but I can't use it. 

Some useful information :

- Application download from MAS
- MacOS 13.3.1
- API Version 1.16.1

**Comment by NattyNarwhal** [comment]
* Did you get any prompts for your keychain password and to allow or deny it?
* When you update the password for the server when editing the settings for it, do you get any error? A Keychain failure should be shown.
* Do you see any entries in Keychain Access? For example, it looks like this for me when I search for the server, and look at allowed applications:
  *  ![Screenshot 2023-04-30 at 6 19 55 PM](https://user-images.githubusercontent.com/3161292/235376730-505ac175-3761-4ca4-985c-da35451d66f9.png)
  *  ![Screenshot 2023-04-30 at 6 20 15 PM](https://user-images.githubusercontent.com/3161292/235376745-0a6e5f3b-94f4-4a27-9658-5de7bf9e9e25.png)
* Does this happen with the non-MAS version?

**Comment by pierrec18** [comment]
Hi

- I probably have a prompt for an access to the keychain initially but I don't get it anymore. (after reinstall or after the creation of a new server)
- No error when I update the password
- It's empty in the keychain. I try to create a keychain in the keychain called "session" and give access Submariner to it and same result.
- I try non-MAS version, it's the same

I don't know if it can help but my server have an address is https://subdomain.domain.me but I also try with the local IP and the result is still the same.

**Comment by NattyNarwhal** [comment]
Do you see anything in Console.app related to Keychain when you try saving the password?

If you have Xcode installed and don't mind building from source, try the latest commit. The Keychain handling code was rewritten in Swift, but should be functionally/logically identical. Put breakpoints on all the Keychain functions ([fetch](https://github.com/NattyNarwhal/Submariner/blob/master/Submariner/SBServer.swift#L166), [adding](https://github.com/NattyNarwhal/Submariner/blob/master/Submariner/SBServer.swift#L215), [updating](https://github.com/NattyNarwhal/Submariner/blob/master/Submariner/SBServer.swift#L221), [updating](https://github.com/NattyNarwhal/Submariner/blob/master/Submariner/SBServer.swift#L256)), and try updating your password again.

**Comment by pierrec18** [comment]
Here are the few lines about the Submariner and the keychain. I imagine this is the error, but I have no idea how to fix it.
[log.txt](https://github.com/NattyNarwhal/Submariner/files/11366977/log.txt)

**Comment by NattyNarwhal** [comment]
This is pretty weird looking. I think the `class genp` is a hint though - I noticed in the older version, I mixed up [generic password](https://github.com/NattyNarwhal/Submariner/blob/v2.1.1/Submariner/SBServer.m#L294) with [internet password](https://github.com/NattyNarwhal/Submariner/blob/v2.1.1/Submariner/SBServer.m#L225), which I fixed in the latest code in Git. That might be a red herring though - if it was a mix-up, I'd expect it to be in Keychain but not able to find it the next time? Worst case, I'd recommend trying the latest from Git, either build it yourself, or try the (unsigned, so you'll need to right-click->open) CI-built one [here](https://github.com/NattyNarwhal/Submariner/suites/12582587117/artifacts/672855545).

FWIW, years ago, I did deal with a corrupt keychain database that prevented me from making an account in Mail.app. I wonder if this is another case of corruption. The solution for it was to reset the login and local keychains from Keychain Access. It is annoying because you'll lose the saved passwords in it and have to sign into i.e. iCloud again, but it did work for me.

**Comment by NattyNarwhal** [comment]
Oh, [there's the error being thrown in Keychain](https://github.com/apple-oss-distributions/Security/blob/e4ea024c9bbd3bfda30ec6df270bfb4c7438d1a9/keychain/securityd/SecItemDb.c#L84). I suspect it is a mix-up between generic/internet passwords. [path](https://developer.apple.com/documentation/security/ksecattrpath) is an attribute of an internet password, but not a generic one. Trying the latest build might solve the issue if that's the case.

**Comment by pierrec18** [comment]
I am trying your build but it crashes when I try to save my server and I do not have Xcode to try to compile it myself 😕
[log2.txt](https://github.com/NattyNarwhal/Submariner/files/11367297/log2.txt)

**Comment by NattyNarwhal** [comment]
Could you try this build? It's of the latest code from Git plus additional logging for Keychain.
[Submariner-2.2-KeychainTest.zip](https://github.com/NattyNarwhal/Submariner/files/11367593/Submariner-2.2-KeychainTest.zip)

**Comment by pierrec18** [comment]
I'm sorry but the app is still crashing when I try to save the server.

[Submariner-2023-05-01-213655.ips.zip](https://github.com/NattyNarwhal/Submariner/files/11367628/Submariner-2023-05-01-213655.ips.zip)

**Comment by NattyNarwhal** [comment]
I think it might be a null object made when it reconstructs the URL [here](https://github.com/NattyNarwhal/Submariner/blob/master/Submariner/SBEditServerController.m#L69), causing a crash on the next line. I've attached another build that adds some logging there. Can you show the console output for this build? It'll log what the value of the string and the constructed NSURL will be.
[Submariner-2.2-KeychainTest2.zip](https://github.com/NattyNarwhal/Submariner/files/11367772/Submariner-2.2-KeychainTest2.zip)

**Comment by NattyNarwhal** [comment]
I've found and identified the crash.

The null resource name is a different regression introduced in the rewrite of that class to Swift. The setter for resourceName assumed there was always a previous resource name. I'm going to push a fix for these issues, and probably cut 2.2 soon.

Thanks for helping identify this!
